name: Build and Deploy

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - name: Deploy React to GitHub Pages
      # You may pin to the exact commit or the version.
      # uses: bitovi/github-actions-react-to-github-pages@4cf343888989e21112bce7e59156242a0e1defb3
      uses: bitovi/github-actions-react-to-github-pages@v1.2.4
      with:
        # Specifies if this action should checkout the code
        checkout: true
        # Specifies whether to use cone-mode when doing a sparse checkout. maps to actions/checkout inputs.sparse-checkout-cone-mode
        checkout-sparse-checkout-cone-mode: true
        # Specifies the command to run the installation.
        install_command: npm i
        # Specifies the command to run after the install command for the build
        build_command: npm run build
        # Specifies if the action should cache npm dependencies.
        caching: true
          
